<?php
//
$gameinfos = [
	'game_name' => clienttranslate("Galactic Era"),
//	'designer' => 'Channing Jones',
//	'artist' => 'Diego Sanchez',
//	'year' => 2021,
	'publisher' => 'Seajay Games',
	'publisher_website' => 'https://www.facebook.com/seajaygames/',
	'publisher_bgg_id' => 42522,
	'bgg_id' => 281676,
	'players' => [1, 2, 3, 4, 5, 6],
	'suggest_player_number' => 4,
	'not_recommend_player_number' => [],
	'estimated_duration' => 180,
	'fast_additional_time' => 120,
	'medium_additional_time' => 240,
	'slow_additional_time' => 480,
	'tie_breaker_description' => "If players are tied then the one with the highest number of stars among the tied wins. If this is also a tie, then use the turn order. The player who is first in turn order among those tied wins.",
	'tie_breaker_split' => [10, 1],
	'losers_not_ranked' => true,
	'db_undo_support' => false,
	'is_beta' => 1,
	'is_coop' => 0,
//	'complexity' => 5,
//	'luck' => 1,
//	'strategy' => 5,
//	'diplomacy' => 3,
	'player_colors' => ['FF3333', '00CC00', '6666FF', 'FF9900', 'CD1FCD', 'FFFF00'],
	'favorite_colors_support' => false,
	'disable_player_order_swap_on_rematch' => true,
	'game_interface_width' => ['min' => 804 + 100, 'max' => null],
//	'presentation' => [
//		totranslate("Galactic Era is an epic space empire builder boardgame from Seajay Games. Each player controls a fledgling space-faring civilization expanding into the galaxy. You will explore distant planets and take them over, advance your technologies, trade with allies and battle your enemies."),
//	],
];
